language: node_js
branches:
  only:
  - master
node_js:
  - node
  - 10
  - 8
stages:
  - build
  - test
  - name: deploy
    if: branch = master
cache:
  yarn: true
  directories:
  - node_modules
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
jobs:
  include:
    - stage: build
      script: yarn build
    - stage: test
      script: yarn test
    - stage: deploy
      node_js: node
      script: yarn release
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

